ARG DEMO_IMAGE=demo
FROM $DEMO_IMAGE

ARG SNYK_TOKEN

RUN apt-get -q update && \
    apt-get install -y curl

RUN curl -sL https://deb.nodesource.com/setup_13.x | bash -
RUN apt-get install -y nodejs

RUN npm install -g snyk

RUN snyk test
