ARG DEMO_IMAGE=demo
FROM $DEMO_IMAGE

ARG AQUA_TOKEN

RUN apt-get -q update && \
    apt-get install -yq curl && \
    apt-get clean

RUN curl -s -o /microscanner https://get.aquasec.com/microscanner && \
    chmod +x /microscanner && \
    /microscanner ${AQUA_TOKEN} && \
    rm -rf /microscanner
