version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build docker image
          command: |
              docker build \
              -t "demo:$CIRCLE_SHA1" \
              .

#      - run:
#          name: Run Snyk on dependencies
#          command: |
#              docker build \
#              -f Dockerfile.snyk \
#              --build-arg SNYK_TOKEN="$SNYK_TOKEN" \
#              --build-arg DEMO_IMAGE="demo:$CIRCLE_SHA1" \
#              .
#
#      - run:
#          name: Run Aqua on image
#          command: |
#              docker build \
#              -f Dockerfile.aqua \
#              --build-arg AQUA_TOKEN="$AQUA_TOKEN" \
#              --build-arg DEMO_IMAGE="demo:$CIRCLE_SHA1" \
#              .

      - store_artifacts:
          path: test-reports
          destination: test-reports
